echo Preparing molecules and reactions...
synsplore prepare -c configs/prepare.yaml

echo Featurizing molecules...
synsplore featurize molecules -c configs/molfeats.yaml

echo Featurizing reactions...
synsplore featurize reactions -c configs/rxnfeats.yaml

echo Sampling synthesis routes...
synsplore sample -c configs/sample.yaml

echo Featurizing routes and product pharmacophores...
synsplore featurize routes -c configs/roufeats.yaml 